package org.sableos.titan2.keyboard.core

// Generated by tools/gen_indic_rows.py from the Devanagari InScript layout.
// Layouts verified against Indic Keyboard (Apache-2.0).
internal object IndicRows {
    val devN = listOf("ौ ै ा ी ू ब ह ग द ज ड ़", "ो े ् ि ु प र क त च ट", "ृ ं म न व ल स य ः")
    val devS = listOf("औ ऐ आ ई ऊ भ ङ घ ध झ ढ ञ", "ओ ए अ इ उ फ ऱ ख थ छ ठ", "ऋ ँ ण ऩ ळ ऴ श ष ऽ ॐ")
    val devMore = mapOf(
        "े" to listOf("ॆ", "ॅ"), "ो" to listOf("ॊ", "ॉ"), "ए" to listOf("ऎ", "ऍ"),
        "ओ" to listOf("ऒ", "ऑ"), "क" to listOf("क्ष", "क़"), "ख" to listOf("ख़"),
        "ग" to listOf("ग़"), "ज" to listOf("ज्ञ", "ज़"), "ड" to listOf("ड़"),
        "ढ" to listOf("ढ़"), "फ" to listOf("फ़"), "य" to listOf("य़"), "त" to listOf("त्र"),
        "श" to listOf("श्र"), "र" to listOf("्र", "र्"), "ऋ" to listOf("ॠ", "ऌ")
    )
    val gujN = listOf("ૌ ૈ ા ી ૂ બ હ ગ દ જ ડ ઼", "ો ે ્ િ ુ પ ર ક ત ચ ટ", "ૃ ં મ ન વ લ સ ય ઃ")
    val gujS = listOf("ઔ ઐ આ ઈ ઊ ભ ઙ ઘ ધ ઝ ઢ ઞ", "ઓ એ અ ઇ ઉ ફ ખ થ છ ઠ", "ઋ ઁ ણ ળ શ ષ ઽ ૐ")
    val gujMore = mapOf(
        "ે" to listOf("ૅ"), "ો" to listOf("ૉ"), "એ" to listOf("ઍ"),
        "ઓ" to listOf("ઑ"), "ક" to listOf("ક્ષ", "ક઼"), "ખ" to listOf("ખ઼"), "ગ" to listOf("ગ઼"),
        "જ" to listOf("જ્ઞ", "જ઼"), "ડ" to listOf("ડ઼"), "ઢ" to listOf("ઢ઼"),
        "ફ" to listOf(
            "ફ઼"
        ),
        "ય" to listOf("ય઼"), "ત" to listOf("ત્ર"), "શ" to listOf("શ્ર"),
        "ર" to listOf("્ર", "ર્"), "ઋ" to listOf("ૠ", "ઌ")
    )
    val benN = listOf("ৌ ৈ া ী ূ ব হ গ দ জ ড ়", "ো ে ্ ি ু প র ক ত চ ট", "ৃ ং ম ন ল স য ঃ")
    val benS = listOf("ঔ ঐ আ ঈ ঊ ভ ঙ ঘ ধ ঝ ঢ ঞ", "ও এ অ ই উ ফ ড় খ থ ছ ঠ", "ঋ ঁ ণ শ ষ ঽ")
    val benMore = mapOf(
        "ক" to listOf("ক্ষ", "ক়"), "খ" to listOf("খ়"), "গ" to listOf("গ়"),
        "জ" to listOf("জ্ঞ", "জ়"), "ড" to listOf("ড়"), "ঢ" to listOf("ঢ়"), "ফ" to listOf("ফ়"),
        "য" to listOf("য়", "য়"), "ত" to listOf("ত্র", "ৎ"), "শ" to listOf("শ্র"),
        "র" to listOf("্র", "র্"), "ঋ" to listOf("ৠ", "ঌ")
    )
    val panN = listOf("ੌ ੈ ਾ ੀ ੂ ਬ ਹ ਗ ਦ ਜ ਡ ਼", "ੋ ੇ ੍ ਿ ੁ ਪ ਰ ਕ ਤ ਚ ਟ", "ਂ ਮ ਨ ਵ ਲ ਸ ਯ ਃ")
    val panS = listOf("ਔ ਐ ਆ ਈ ਊ ਭ ਙ ਘ ਧ ਝ ਢ ਞ", "ਓ ਏ ਅ ਇ ਉ ਫ ੜ ਖ ਥ ਛ ਠ", "ਁ ਣ ਲ਼ ਸ਼")
    val panMore = mapOf(
        "ਕ" to listOf("ਕ਼"), "ਖ" to listOf("ਖ਼", "ਖ਼"), "ਗ" to listOf("ਗ਼", "ਗ਼"),
        "ਜ" to listOf("ਜ੍ਞ", "ਜ਼", "ਜ਼"), "ਡ" to listOf("ਡ਼"), "ਢ" to listOf("ਢ਼"),
        "ਫ" to listOf("ਫ਼", "ਫ਼"), "ਯ" to listOf("ਯ਼"), "ਤ" to listOf("ਤ੍ਰ"),
        "ਸ਼" to listOf("ਸ਼੍ਰ"), "ਰ" to listOf("੍ਰ", "ਰ੍"), "ਅ" to listOf("ੳ", "ੲ"),
        "ਂ" to listOf("ੰ", "ੱ")
    )
    val tamN = listOf("ௌ ை ா ீ ூ ஹ ஜ", "ோ ே ் ி ு ப ர க த ச ட", "ஂ ம ந வ ல ஸ ய ஃ ெ ொ")
    val tamS = listOf("ஔ ஐ ஆ ஈ ஊ ங ஞ", "ஓ ஏ அ இ உ ற", "ண ன ள ழ ஶ ஷ ௐ எ ஒ")
    val tamMore = mapOf("க" to listOf("க்ஷ"))
    val telN = listOf("ౌ ై ా ీ ూ బ హ గ ద జ డ ఼", "ో ే ్ ి ు ప ర క త చ ట", "ృ ం మ న వ ల స య ః ె ొ")
    val telS = listOf("ఔ ఐ ఆ ఈ ఊ భ ఙ ఘ ధ ఝ ఢ ఞ", "ఓ ఏ అ ఇ ఉ ఫ ఱ ఖ థ ఛ ఠ", "ఋ ఁ ణ ళ ఴ శ ష ఽ ఎ ఒ")
    val telMore = mapOf(
        "క" to listOf("క్ష", "క఼"), "ఖ" to listOf("ఖ఼"), "గ" to listOf("గ఼"),
        "జ" to listOf("జ్ఞ", "జ఼"), "డ" to listOf("డ఼"), "ఢ" to listOf("ఢ఼"), "ఫ" to listOf("ఫ఼"),
        "య" to listOf("య఼"), "త" to listOf("త్ర"), "శ" to listOf("శ్ర"),
        "ర" to listOf("్ర", "ర్"), "ఋ" to listOf("ౠ", "ఌ")
    )
    val kanN = listOf("ೌ ೈ ಾ ೀ ೂ ಬ ಹ ಗ ದ ಜ ಡ ಼", "ೋ ೇ ್ ಿ ು ಪ ರ ಕ ತ ಚ ಟ", "ೃ ಂ ಮ ನ ವ ಲ ಸ ಯ ಃ ೆ ೊ")
    val kanS = listOf("ಔ ಐ ಆ ಈ ಊ ಭ ಙ ಘ ಧ ಝ ಢ ಞ", "ಓ ಏ ಅ ಇ ಉ ಫ ಱ ಖ ಥ ಛ ಠ", "ಋ ಁ ಣ ಳ ೞ ಶ ಷ ಽ ಎ ಒ")
    val kanMore = mapOf(
        "ಕ" to listOf("ಕ್ಷ", "ಕ಼"), "ಖ" to listOf("ಖ಼"), "ಗ" to listOf("ಗ಼"),
        "ಜ" to listOf("ಜ್ಞ", "ಜ಼"), "ಡ" to listOf("ಡ಼"), "ಢ" to listOf("ಢ಼"), "ಫ" to listOf("ಫ಼"),
        "ಯ" to listOf("ಯ಼"), "ತ" to listOf("ತ್ರ"), "ಶ" to listOf("ಶ್ರ"),
        "ರ" to listOf("್ರ", "ರ್"), "ಋ" to listOf("ೠ", "ಌ")
    )
    val malN = listOf("ൌ ൈ ാ ീ ൂ ബ ഹ ഗ ദ ജ ഡ", "ോ േ ് ി ു പ ര ക ത ച ട", "ൃ ം മ ന വ ല സ യ ഃ െ ൊ")
    val malS = listOf("ഔ ഐ ആ ഈ ഊ ഭ ങ ഘ ധ ഝ ഢ ഞ", "ഓ ഏ അ ഇ ഉ ഫ റ ഖ ഥ ഛ ഠ", "ഋ ഁ ണ ഩ ള ഴ ശ ഷ ഽ എ ഒ")
    val malMore = mapOf(
        "ക" to listOf("ക്ഷ", "ൿ"), "ജ" to listOf("ജ്ഞ"), "ത" to listOf("ത്ര"),
        "ശ" to listOf("ശ്ര"), "ര" to listOf("്ര", "ര്", "ർ"), "ഋ" to listOf("ൠ", "ഌ"),
        "ണ" to listOf("ൺ"), "ന" to listOf("ൻ"), "ല" to listOf("ൽ"), "ള" to listOf("ൾ"),
        "ൌ" to listOf("ൗ")
    )
}
