package org.sableos.titan2.keyboard.core

// Generated by tools/gen_phonetic.py. Roman scheme: see PhoneticComposer. Review with native speakers before shipping.
object PhoneticTables {
    val devanagari = PhoneticTable(
        consonants = mapOf(
            "k" to "क", "kh" to "ख", "g" to "ग",
            "gh" to "घ", "c" to "क", "ch" to "च", "chh" to "छ", "j" to "ज", "jh" to "झ", "T" to "ट",
            "Th" to "ठ", "D" to "ड", "Dh" to "ढ", "N" to "ण", "t" to "त", "th" to "थ", "d" to "द",
            "dh" to "ध", "n" to "न", "p" to "प", "ph" to "फ", "b" to "ब", "bh" to "भ",
            "m" to "म", "y" to "य", "r" to "र", "l" to "ल", "v" to "व", "w" to "व",
            "sh" to "श", "Sh" to "ष", "s" to "स", "h" to "ह", "L" to "ळ", "zh" to "ऴ",
            "R" to "ऱ", "nh" to "ऩ", "x" to "क्ष", "gy" to "ज्ञ", "GY" to "ज्ञ",
            "q" to "क़", "f" to "फ़", "z" to "ज़"
        ),
        vowels = mapOf(
            "a" to ("अ" to ""), "aa" to ("आ" to "ा"), "A" to ("आ" to "ा"),
            "i" to ("इ" to "ि"), "ii" to ("ई" to "ी"), "I" to ("ई" to "ी"), "ee" to ("ई" to "ी"),
            "u" to ("उ" to "ु"), "uu" to ("ऊ" to "ू"), "U" to ("ऊ" to "ू"), "oo" to ("ऊ" to "ू"),
            "e" to ("ए" to "े"), "E" to ("ए" to "े"), "ai" to ("ऐ" to "ै"),
            "o" to ("ओ" to "ो"), "O" to ("ओ" to "ो"), "au" to ("औ" to "ौ"),
            "RRi" to ("ऋ" to "ृ"), "Ri" to ("ऋ" to "ृ")
        ),
        marks = mapOf("M" to "ं", "MM" to "ँ", "~" to "ँ", "H" to "ः"),
        specials = mapOf("OM" to "ॐ"),
        virama = "्",
        finalVirama = false
    )
    val gujarati =
        PhoneticTable(
            consonants = mapOf(
                "k" to "ક", "kh" to "ખ", "g" to "ગ", "gh" to "ઘ",
                "c" to "ક", "ch" to "ચ", "chh" to "છ", "j" to "જ", "jh" to "ઝ", "T" to "ટ",
                "Th" to "ઠ",
                "D" to "ડ", "Dh" to "ઢ", "N" to "ણ", "t" to "ત", "th" to "થ", "d" to "દ",
                "dh" to "ધ",
                "n" to "ન", "p" to "પ", "ph" to "ફ", "b" to "બ", "bh" to "ભ", "m" to "મ",
                "y" to "ય",
                "r" to "ર", "l" to "લ", "v" to "વ", "w" to "વ", "sh" to "શ", "Sh" to "ષ",
                "s" to "સ", "h" to "હ", "L" to "ળ", "zh" to "ળ", "nh" to "ન", "x" to "ક્ષ",
                "gy" to "જ્ઞ", "GY" to "જ્ઞ", "q" to "ક઼", "f" to "ફ઼", "z" to "જ઼"
            ),
            vowels = mapOf(
                "a" to ("અ" to ""), "aa" to ("આ" to "ા"), "A" to ("આ" to "ા"),
                "i" to ("ઇ" to "િ"), "ii" to ("ઈ" to "ી"), "I" to ("ઈ" to "ી"),
                "ee" to ("ઈ" to "ી"),
                "u" to ("ઉ" to "ુ"), "uu" to ("ઊ" to "ૂ"), "U" to ("ઊ" to "ૂ"),
                "oo" to ("ઊ" to "ૂ"),
                "e" to ("એ" to "ે"), "E" to ("એ" to "ે"), "ai" to ("ઐ" to "ૈ"),
                "o" to ("ઓ" to "ો"), "O" to ("ઓ" to "ો"), "au" to ("ઔ" to "ૌ"),
                "RRi" to ("ઋ" to "ૃ"), "Ri" to ("ઋ" to "ૃ")
            ),
            marks = mapOf("M" to "ં", "MM" to "ઁ", "~" to "ઁ", "H" to "ઃ"),
            specials = mapOf("OM" to "ૐ"),
            virama = "્",
            finalVirama = false
        )
    val bengali = PhoneticTable(
        consonants = mapOf(
            "k" to "ক", "kh" to "খ", "g" to "গ", "gh" to "ঘ",
            "c" to "ক", "ch" to "চ", "chh" to "ছ", "j" to "জ", "jh" to "ঝ", "T" to "ট", "Th" to "ঠ",
            "D" to "ড", "Dh" to "ঢ", "N" to "ণ", "t" to "ত", "th" to "থ", "d" to "দ", "dh" to "ধ",
            "n" to "ন", "p" to "প", "ph" to "ফ", "b" to "ব", "bh" to "ভ", "m" to "ম", "y" to "য",
            "r" to "র", "l" to "ল", "v" to "ব", "w" to "ব", "sh" to "শ", "Sh" to "ষ",
            "s" to "স", "h" to "হ", "L" to "ল", "zh" to "ল", "R" to "ড়", "nh" to "ন",
            "x" to "ক্ষ", "gy" to "জ্ঞ", "GY" to "জ্ঞ", "q" to "ক়", "f" to "ফ়",
            "z" to "জ়"
        ),
        vowels = mapOf(
            "a" to ("অ" to ""), "aa" to ("আ" to "া"), "A" to ("আ" to "া"),
            "i" to ("ই" to "ি"), "ii" to ("ঈ" to "ী"), "I" to ("ঈ" to "ী"), "ee" to ("ঈ" to "ী"),
            "u" to ("উ" to "ু"), "uu" to ("ঊ" to "ূ"), "U" to ("ঊ" to "ূ"), "oo" to ("ঊ" to "ূ"),
            "e" to ("এ" to "ে"), "E" to ("এ" to "ে"), "ai" to ("ঐ" to "ৈ"),
            "o" to ("ও" to "ো"), "O" to ("ও" to "ো"), "au" to ("ঔ" to "ৌ"),
            "RRi" to ("ঋ" to "ৃ"), "Ri" to ("ঋ" to "ৃ")
        ),
        marks = mapOf("M" to "ং", "MM" to "ঁ", "~" to "ঁ", "H" to "ঃ"),
        specials = mapOf(),
        virama = "্",
        finalVirama = false
    )
    val gurmukhi =
        PhoneticTable(
            consonants = mapOf(
                "k" to "ਕ", "kh" to "ਖ", "g" to "ਗ", "gh" to "ਘ",
                "c" to "ਕ", "ch" to "ਚ", "chh" to "ਛ", "j" to "ਜ", "jh" to "ਝ", "T" to "ਟ",
                "Th" to "ਠ",
                "D" to "ਡ", "Dh" to "ਢ", "N" to "ਣ", "t" to "ਤ", "th" to "ਥ", "d" to "ਦ",
                "dh" to "ਧ",
                "n" to "ਨ", "p" to "ਪ", "ph" to "ਫ", "b" to "ਬ", "bh" to "ਭ", "m" to "ਮ",
                "y" to "ਯ",
                "r" to "ਰ", "l" to "ਲ", "v" to "ਵ", "w" to "ਵ", "sh" to "ਸ਼", "s" to "ਸ",
                "h" to "ਹ", "L" to "ਲ਼", "zh" to "ਲ", "R" to "ੜ", "nh" to "ਨ", "gy" to "ਜ੍ਞ",
                "GY" to "ਜ੍ਞ", "q" to "ਕ਼", "f" to "ਫ਼", "z" to "ਜ਼"
            ),
            vowels = mapOf(
                "a" to ("ਅ" to ""), "aa" to ("ਆ" to "ਾ"), "A" to ("ਆ" to "ਾ"),
                "i" to ("ਇ" to "ਿ"), "ii" to ("ਈ" to "ੀ"), "I" to ("ਈ" to "ੀ"),
                "ee" to ("ਈ" to "ੀ"),
                "u" to ("ਉ" to "ੁ"), "uu" to ("ਊ" to "ੂ"), "U" to ("ਊ" to "ੂ"),
                "oo" to ("ਊ" to "ੂ"),
                "e" to ("ਏ" to "ੇ"), "E" to ("ਏ" to "ੇ"), "ai" to ("ਐ" to "ੈ"),
                "o" to ("ਓ" to "ੋ"), "O" to ("ਓ" to "ੋ"), "au" to ("ਔ" to "ੌ")
            ),
            marks = mapOf("M" to "ੰ", "MM" to "ਂ", "~" to "ਂ", "H" to "ਃ"),
            specials = mapOf(),
            virama = "੍",
            finalVirama = false
        )
    val tamil = PhoneticTable(
        consonants = mapOf(
            "k" to "க", "kh" to "க", "g" to "க", "gh" to "க",
            "c" to "க", "ch" to "ச", "chh" to "ச", "j" to "ஜ", "jh" to "ஜ", "T" to "ட", "Th" to "ட",
            "D" to "ட", "Dh" to "ட", "N" to "ண", "t" to "த", "th" to "த", "d" to "த", "dh" to "த",
            "n" to "ந", "p" to "ப", "ph" to "ப", "b" to "ப", "bh" to "ப", "m" to "ம", "y" to "ய",
            "r" to "ர", "l" to "ல", "v" to "வ", "w" to "வ", "sh" to "ஶ", "Sh" to "ஷ",
            "s" to "ஸ", "h" to "ஹ", "L" to "ள", "zh" to "ழ", "R" to "ற", "nh" to "ன",
            "x" to "க்ஷ", "q" to "க", "f" to "ப", "z" to "ஜ", "ng" to "ங",
            "nj" to "ஞ"
        ),
        vowels = mapOf(
            "a" to ("அ" to ""), "aa" to ("ஆ" to "ா"), "A" to ("ஆ" to "ா"),
            "i" to ("இ" to "ி"), "ii" to ("ஈ" to "ீ"), "I" to ("ஈ" to "ீ"), "ee" to ("ஈ" to "ீ"),
            "u" to ("உ" to "ு"), "uu" to ("ஊ" to "ூ"), "U" to ("ஊ" to "ூ"), "oo" to ("ஊ" to "ூ"),
            "e" to ("எ" to "ெ"), "E" to ("ஏ" to "ே"), "ai" to ("ஐ" to "ை"),
            "o" to ("ஒ" to "ொ"), "O" to ("ஓ" to "ோ"), "au" to ("ஔ" to "ௌ")
        ),
        marks = mapOf("M" to "ஂ", "H" to "ஃ"),
        specials = mapOf("OM" to "ௐ"),
        virama = "்",
        finalVirama = true
    )
    val telugu = PhoneticTable(
        consonants = mapOf(
            "k" to "క", "kh" to "ఖ", "g" to "గ", "gh" to "ఘ",
            "c" to "క", "ch" to "చ", "chh" to "ఛ", "j" to "జ", "jh" to "ఝ", "T" to "ట", "Th" to "ఠ",
            "D" to "డ", "Dh" to "ఢ", "N" to "ణ", "t" to "త", "th" to "థ", "d" to "ద", "dh" to "ధ",
            "n" to "న", "p" to "ప", "ph" to "ఫ", "b" to "బ", "bh" to "భ", "m" to "మ", "y" to "య",
            "r" to "ర", "l" to "ల", "v" to "వ", "w" to "వ", "sh" to "శ", "Sh" to "ష",
            "s" to "స", "h" to "హ", "L" to "ళ", "zh" to "ఴ", "R" to "ఱ", "nh" to "న",
            "x" to "క్ష", "gy" to "జ్ఞ", "GY" to "జ్ఞ", "q" to "క", "f" to "ఫ",
            "z" to "జ", "ng" to "ఙ", "nj" to "ఞ"
        ),
        vowels = mapOf(
            "a" to ("అ" to ""), "aa" to ("ఆ" to "ా"), "A" to ("ఆ" to "ా"),
            "i" to ("ఇ" to "ి"), "ii" to ("ఈ" to "ీ"), "I" to ("ఈ" to "ీ"), "ee" to ("ఈ" to "ీ"),
            "u" to ("ఉ" to "ు"), "uu" to ("ఊ" to "ూ"), "U" to ("ఊ" to "ూ"), "oo" to ("ఊ" to "ూ"),
            "e" to ("ఎ" to "ె"), "E" to ("ఏ" to "ే"), "ai" to ("ఐ" to "ై"),
            "o" to ("ఒ" to "ొ"), "O" to ("ఓ" to "ో"), "au" to ("ఔ" to "ౌ"),
            "RRi" to ("ఋ" to "ృ")
        ),
        marks = mapOf("M" to "ం", "MM" to "ఁ", "~" to "ఁ", "H" to "ః"),
        specials = mapOf(),
        virama = "్",
        finalVirama = true
    )
    val kannada = PhoneticTable(
        consonants = mapOf(
            "k" to "ಕ", "kh" to "ಖ", "g" to "ಗ", "gh" to "ಘ",
            "c" to "ಕ", "ch" to "ಚ", "chh" to "ಛ", "j" to "ಜ", "jh" to "ಝ", "T" to "ಟ", "Th" to "ಠ",
            "D" to "ಡ", "Dh" to "ಢ", "N" to "ಣ", "t" to "ತ", "th" to "ಥ", "d" to "ದ", "dh" to "ಧ",
            "n" to "ನ", "p" to "ಪ", "ph" to "ಫ", "b" to "ಬ", "bh" to "ಭ", "m" to "ಮ", "y" to "ಯ",
            "r" to "ರ", "l" to "ಲ", "v" to "ವ", "w" to "ವ", "sh" to "ಶ", "Sh" to "ಷ",
            "s" to "ಸ", "h" to "ಹ", "L" to "ಳ", "zh" to "ೞ", "R" to "ಱ", "nh" to "ನ",
            "x" to "ಕ್ಷ", "gy" to "ಜ್ಞ", "GY" to "ಜ್ಞ", "q" to "ಕ", "f" to "ಫ",
            "z" to "ಜ", "ng" to "ಙ", "nj" to "ಞ"
        ),
        vowels = mapOf(
            "a" to ("ಅ" to ""), "aa" to ("ಆ" to "ಾ"), "A" to ("ಆ" to "ಾ"),
            "i" to ("ಇ" to "ಿ"), "ii" to ("ಈ" to "ೀ"), "I" to ("ಈ" to "ೀ"), "ee" to ("ಈ" to "ೀ"),
            "u" to ("ಉ" to "ು"), "uu" to ("ಊ" to "ೂ"), "U" to ("ಊ" to "ೂ"), "oo" to ("ಊ" to "ೂ"),
            "e" to ("ಎ" to "ೆ"), "E" to ("ಏ" to "ೇ"), "ai" to ("ಐ" to "ೈ"),
            "o" to ("ಒ" to "ೊ"), "O" to ("ಓ" to "ೋ"), "au" to ("ಔ" to "ೌ"),
            "RRi" to ("ಋ" to "ೃ")
        ),
        marks = mapOf("M" to "ಂ", "MM" to "ಁ", "~" to "ಁ", "H" to "ಃ"),
        specials = mapOf(),
        virama = "್",
        finalVirama = true
    )
    val malayalam = PhoneticTable(
        consonants = mapOf(
            "k" to "ക", "kh" to "ഖ", "g" to "ഗ",
            "gh" to "ഘ", "c" to "ക", "ch" to "ച", "chh" to "ഛ", "j" to "ജ", "jh" to "ഝ", "T" to "ട",
            "Th" to "ഠ", "D" to "ഡ", "Dh" to "ഢ", "N" to "ണ", "t" to "ത", "th" to "ഥ", "d" to "ദ",
            "dh" to "ധ", "n" to "ന", "p" to "പ", "ph" to "ഫ", "b" to "ബ", "bh" to "ഭ",
            "m" to "മ", "y" to "യ", "r" to "ര", "l" to "ല", "v" to "വ", "w" to "വ",
            "sh" to "ശ", "Sh" to "ഷ", "s" to "സ", "h" to "ഹ", "L" to "ള", "zh" to "ഴ",
            "R" to "റ", "nh" to "ഩ", "x" to "ക്ഷ", "gy" to "ജ്ഞ", "GY" to "ജ്ഞ",
            "q" to "ക", "f" to "ഫ", "z" to "ജ", "ng" to "ങ", "nj" to "ഞ"
        ),
        vowels = mapOf(
            "a" to ("അ" to ""), "aa" to ("ആ" to "ാ"), "A" to ("ആ" to "ാ"),
            "i" to ("ഇ" to "ി"), "ii" to ("ഈ" to "ീ"), "I" to ("ഈ" to "ീ"), "ee" to ("ഈ" to "ീ"),
            "u" to ("ഉ" to "ു"), "uu" to ("ഊ" to "ൂ"), "U" to ("ഊ" to "ൂ"), "oo" to ("ഊ" to "ൂ"),
            "e" to ("എ" to "െ"), "E" to ("ഏ" to "േ"), "ai" to ("ഐ" to "ൈ"),
            "o" to ("ഒ" to "ൊ"), "O" to ("ഓ" to "ോ"), "au" to ("ഔ" to "ൌ"),
            "RRi" to ("ഋ" to "ൃ")
        ),
        marks = mapOf("M" to "ം", "MM" to "ഁ", "~" to "ഁ", "H" to "ഃ"),
        specials = mapOf(),
        virama = "്",
        finalVirama = true
    )
}
