#!/usr/bin/env python3
"""Generates PhoneticTables.kt: Roman-letter ("phonetic") typing tables for the Indic scripts.

One Roman scheme is defined over Devanagari phonemes (ITRANS-like, case sensitive: T D N L Sh are the retroflex/aspirate forms)
and mapped into every script by Unicode name (indic_common.py). Letters a script lacks fall back to the closest one it has
(Tamil kh gh -> க, Bengali v -> ব, and so on). Prints Kotlin to stdout.
"""
from indic_common import *

CONS = {"k": "क", "kh": "ख", "g": "ग", "gh": "घ", "c": "क", "ch": "च", "chh": "छ", "j": "ज", "jh": "झ",
        "T": "ट", "Th": "ठ", "D": "ड", "Dh": "ढ", "N": "ण", "t": "त", "th": "थ", "d": "द", "dh": "ध", "n": "न",
        "p": "प", "ph": "फ", "b": "ब", "bh": "भ", "m": "म", "y": "य", "r": "र", "l": "ल", "v": "व", "w": "व",
        "sh": "श", "Sh": "ष", "s": "स", "h": "ह", "L": "ळ", "zh": "ऴ", "R": "ऱ", "nh": "ऩ",
        "x": "क्ष", "gy": "ज्ञ", "GY": "ज्ञ", "q": "क़", "f": "फ़", "z": "ज़"}
# Only where the script has these as ordinary sounds (south Indian scripts write ng / nj routinely).
CONS_DRAVIDIAN = {"ng": "ङ", "nj": "ञ"}
VOW = {"a": ("अ", ""), "aa": ("आ", "ा"), "A": ("आ", "ा"), "i": ("इ", "ि"), "ii": ("ई", "ी"), "I": ("ई", "ी"), "ee": ("ई", "ी"),
       "u": ("उ", "ु"), "uu": ("ऊ", "ू"), "U": ("ऊ", "ू"), "oo": ("ऊ", "ू"),
       "e": ("ए", "े"), "E": ("ए", "े"), "ai": ("ऐ", "ै"), "o": ("ओ", "ो"), "O": ("ओ", "ो"), "au": ("औ", "ौ"),
       "RRi": ("ऋ", "ृ")}
VOW_NORTH = {"Ri": ("ऋ", "ृ")}
# South Indian scripts: e/o are the SHORT vowels, E/O the long ones.
VOW_DRAVIDIAN = {"e": ("ऎ", "ॆ"), "E": ("ए", "े"), "o": ("ऒ", "ॊ"), "O": ("ओ", "ो")}
MARKS = {"M": "ं", "MM": "ँ", "~": "ँ", "H": "ः"}
SPECIAL = {"OM": "ॐ"}
VIRAMA = "्"
# Closest letter a script has when the exact one is missing (tried in order, Devanagari characters).
FALLBACK = {
    "TAMIL": {"ख": "क", "घ": "क", "ग": "क", "छ": "च", "झ": "ज", "ठ": "ट", "ढ": "ट", "ड": "ट", "थ": "त", "ध": "त", "द": "त",
              "फ": "प", "भ": "प", "ब": "प", "ऩ": "न"},
    "BENGALI": {"व": "ब", "ळ": "ल", "ऴ": "ल", "ऩ": "न"},
    "GURMUKHI": {"ऴ": "ल", "ऩ": "न", "ळ": "ल"},
    "GUJARATI": {"ऴ": "ळ", "ऩ": "न"},
    "KANNADA": {"ऩ": "न"}, "TELUGU": {"ऩ": "न", "ऴ": "ळ"}, "MALAYALAM": {"ऩ": "न"},
}
# Scripts whose words end in a pronounced consonant need an explicit virama; the north Indian ones drop the final schwa.
FINAL_VIRAMA = ("TAMIL", "TELUGU", "KANNADA", "MALAYALAM")

NO_NUKTA = ("TAMIL", "TELUGU", "KANNADA", "MALAYALAM")     # established nukta use is north Indian

def map_tok(tok, script):
    if "\u093C" in tok and script in NO_NUKTA: tok = tok.replace("\u093C", "")
    r = derive_token(tok, script)
    if r: return r
    if "़" in tok:                             # no nukta in this script: use the plain letter
        r = map_tok(tok.replace("़", ""), script)
        if r: return r
    fb = FALLBACK.get(script, {})
    if len(tok) == 1 and tok in fb:
        return derive_token(fb[tok], script)
    return None

def table(script):
    dr = script in SHORT_EO_SCRIPTS
    cons_src = dict(CONS); vow_src = dict(VOW)
    if dr: cons_src.update(CONS_DRAVIDIAN); vow_src.update(VOW_DRAVIDIAN); vow_src.pop("RRi", None); vow_src["RRi"] = ("ऋ", "ृ")
    else: vow_src.update(VOW_NORTH)
    if script == "TAMIL":                         # Tamil has no gy / jny conjunct key
        cons_src.pop("gy"); cons_src.pop("GY")
    cons = {k: v for k, v in ((k, map_tok(t, script)) for k, t in cons_src.items()) if v}
    vows = {}
    for k, (ind, sign) in vow_src.items():
        i = map_tok(ind, script); s = map_tok(sign, script) if sign else ""
        if i and s is not None: vows[k] = (i, s)
    marks = {k: v for k, v in ((k, map_tok(t, script)) for k, t in MARKS.items()) if v}
    if script == "GURMUKHI": marks.update({"M": "\u0A70", "MM": "\u0A02", "~": "\u0A02"})      # tippi is the usual nasal mark
    spec = {k: v for k, v in ((k, map_tok(t, script)) for k, t in SPECIAL.items()) if v}
    return cons, vows, marks, spec, map_tok(VIRAMA, script), script in FINAL_VIRAMA

def km(d): return "mapOf(" + ", ".join('"%s" to "%s"' % (k, v) for k, v in d.items()) + ")"
def kv(d): return "mapOf(" + ", ".join('"%s" to ("%s" to "%s")' % (k, a, b) for k, (a, b) in d.items()) + ")"

NAMES = (("devanagari", "DEVANAGARI"), ("gujarati", "GUJARATI"), ("bengali", "BENGALI"), ("gurmukhi", "GURMUKHI"),
         ("tamil", "TAMIL"), ("telugu", "TELUGU"), ("kannada", "KANNADA"), ("malayalam", "MALAYALAM"))

if __name__ == "__main__":
    print("package org.sableos.titan2.keyboard.core\n")
    print("// Generated by tools/gen_phonetic.py. Roman scheme: see PhoneticComposer. Review with native speakers before shipping.")
    print("object PhoneticTables {")
    for nm, script in NAMES:
        if script == "DEVANAGARI":
            c, v, m, s, vir, fv = {k: t for k, t in CONS.items()}, {k: (a, b) for k, (a, b) in {**VOW, **VOW_NORTH}.items()}, MARKS, SPECIAL, VIRAMA, False
        else:
            c, v, m, s, vir, fv = table(script)
        print(f'    val {nm} = PhoneticTable(consonants = {km(c)},\n        vowels = {kv(v)},\n        marks = {km(m)}, specials = {km(s)}, virama = "{vir}", finalVirama = {str(fv).lower()})')
    print("}")
