#!/usr/bin/env python3
"""Generates the first-party Sable launcher icons from the pinned Phosphor glyphs.

Usage: gen_first_party_icons.py [--check]

Reads third_party/phosphor-icons/ICON_MANIFEST.tsv and glyphs/*.svg (verbatim Phosphor regular SVGs at the commit
pinned in third_party/phosphor-icons/PROVENANCE.md). For every manifest row it writes, under <res_dir>/ (relative
to the sable-src root):

  drawable/<drawable>.xml             legacy full-bleed vector in the SableOS R9 language: 256x256 viewport,
                                      #161C24 tonal rounded background, #F7F9FC glyph at 0.70 scale, per-app
                                      accent bottom rail. Used in-app (logos, shortcuts) and as the pre-26 icon.
  drawable/<drawable>_background.xml  adaptive background: full-bleed #161C24 on the 108dp canvas
  drawable/<drawable>_foreground.xml  adaptive foreground: the glyph centred in the 108dp canvas inside the 66dp
                                      safe zone, with the accent rail under it (also inside the safe zone)
  drawable/<drawable>_monochrome.xml  adaptive monochrome layer (Android 13+ themed icons): the glyph only
  mipmap-anydpi-v26/<drawable>.xml    <adaptive-icon> with background, foreground and monochrome
  mipmap-anydpi-v26/<drawable>_round.xml  the same, for android:roundIcon
  mipmap/<drawable>.xml, mipmap/<drawable>_round.xml
                                      only when legacy_fallback=mipmap (app minSdk < 26): the legacy vector, so
                                      @mipmap/<drawable> resolves before API 26

Manifests point android:icon at @mipmap/<drawable> and android:roundIcon at @mipmap/<drawable>_round.
With --check, writes nothing and exits 1 if any generated file is missing or differs.
"""
import hashlib
import math
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PH = os.path.join(ROOT, "third_party", "phosphor-icons")
BG = "#161C24"
GLYPH = "#F7F9FC"
BG_PATH = "M32,16h192c8.8,0 16,7.2 16,16v192c0,8.8 -7.2,16 -16,16H32c-8.8,0 -16,-7.2 -16,-16V32c0,-8.8 7.2,-16 16,-16z"
RAIL_PATH = "M28,226h200v6H28z"

# Adaptive geometry (dp on the 108dp canvas). The whole 256-unit glyph box is scaled to GLYPH_BOX dp and centred,
# so every point a glyph can draw lies inside the 66dp safe-zone circle; the rail sits under the glyph box.
CANVAS = 108.0
SAFE_DIAMETER = 66.0
GLYPH_BOX = 44.0
GLYPH_SCALE = GLYPH_BOX / 256.0
GLYPH_OFFSET = (CANVAS - GLYPH_BOX) / 2.0
RAIL = (38.0, 76.5, 32.0, 1.5)  # x, y, width, height
ADAPTIVE_RAIL_PATH = "M%g,%gh%gv%gH%gz" % (RAIL[0], RAIL[1], RAIL[2], RAIL[3], RAIL[0])

LEGACY = """<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="256"
    android:viewportHeight="256">
    <path
        android:fillColor="%(bg_color)s"
        android:pathData="%(bg)s" />
    <group
        android:scaleX="0.70"
        android:scaleY="0.70"
        android:translateX="38.4"
        android:translateY="34">
        <path
            android:fillColor="%(glyph_color)s"
            android:pathData="%(glyph)s" />
    </group>
    <path
        android:fillColor="%(accent)s"
        android:pathData="%(rail)s" />
</vector>
"""

HEADER = """<!-- Generated by sable-src/tools/gen_first_party_icons.py from ICON_MANIFEST.tsv; do not edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
"""

GLYPH_GROUP = """    <group
        android:scaleX="%(scale)s"
        android:scaleY="%(scale)s"
        android:translateX="%(offset)s"
        android:translateY="%(offset)s">
        <path
            android:fillColor="%(color)s"
            android:pathData="%(glyph)s" />
    </group>
"""

BACKGROUND = HEADER + """    <path
        android:fillColor="%(bg_color)s"
        android:pathData="M0,0h108v108H0z" />
</vector>
"""

FOREGROUND = HEADER + GLYPH_GROUP + """    <path
        android:fillColor="%(accent)s"
        android:pathData="%(rail)s" />
</vector>
"""

MONOCHROME = HEADER + GLYPH_GROUP + """</vector>
"""

ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by sable-src/tools/gen_first_party_icons.py from ICON_MANIFEST.tsv; do not edit. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/%(name)s_background" />
    <foreground android:drawable="@drawable/%(name)s_foreground" />
    <monochrome android:drawable="@drawable/%(name)s_monochrome" />
</adaptive-icon>
"""

COLUMNS = ("module", "drawable", "glyph", "glyph_svg_sha256", "accent", "origin", "panther_equivalent",
           "res_dir", "legacy_fallback")


def fail(msg):
    sys.exit("ICON_GENERATOR_FAIL: " + msg)


def rows():
    lines = open(os.path.join(PH, "ICON_MANIFEST.tsv"), encoding="utf8").read().strip().split("\n")
    head = tuple(lines[0].split("\t"))
    if head != COLUMNS:
        fail("ICON_MANIFEST.tsv columns must be " + ",".join(COLUMNS))
    out = []
    seen = set()
    for n, ln in enumerate(lines[1:], 2):
        cells = ln.split("\t")
        if len(cells) != len(COLUMNS):
            fail("ICON_MANIFEST.tsv line %d has %d columns" % (n, len(cells)))
        r = dict(zip(COLUMNS, cells))
        if r["module"] in seen:
            fail("duplicate module %s" % r["module"])
        seen.add(r["module"])
        if not re.fullmatch(r"#[0-9A-F]{6}", r["accent"]):
            fail("accent %s of %s must be #RRGGBB (upper case)" % (r["accent"], r["module"]))
        if not re.fullmatch(r"ic_sable_[a-z0-9_]+", r["drawable"]):
            fail("drawable %s must be ic_sable_<name>" % r["drawable"])
        if r["legacy_fallback"] not in ("none", "mipmap"):
            fail("legacy_fallback of %s must be none or mipmap" % r["module"])
        if os.path.isabs(r["res_dir"]) or ".." in r["res_dir"].split("/") or not r["res_dir"].endswith("res"):
            fail("res_dir of %s must be a relative .../res path" % r["module"])
        out.append(r)
    return out


def glyph_path(name, want_sha):
    data = open(os.path.join(PH, "glyphs", name + ".svg"), "rb").read()
    if hashlib.sha256(data).hexdigest() != want_sha:
        fail("glyph %s sha256 differs from ICON_MANIFEST.tsv" % name)
    text = data.decode("utf8")
    d = re.findall(r'<path d="([^"]+)"', text)
    if len(d) != 1 or 'viewBox="0 0 256 256"' not in text:
        fail("glyph %s must be a single path on a 256x256 viewBox" % name)
    return d[0]


def check_safe_zone():
    """Every corner of the glyph box and of the rail must lie inside the safe-zone circle."""
    c, r = CANVAS / 2.0, SAFE_DIAMETER / 2.0
    lo, hi = GLYPH_OFFSET, GLYPH_OFFSET + GLYPH_BOX
    x, y, w, h = RAIL
    corners = [(lo, lo), (lo, hi), (hi, lo), (hi, hi), (x, y), (x + w, y), (x, y + h), (x + w, y + h)]
    for px, py in corners:
        if math.hypot(px - c, py - c) > r:
            fail("adaptive geometry leaves the %gdp safe zone at (%g, %g)" % (SAFE_DIAMETER, px, py))
    if y < hi:
        fail("rail overlaps the glyph box")


def render(r):
    glyph = glyph_path(r["glyph"], r["glyph_svg_sha256"])
    name = r["drawable"]
    legacy = LEGACY % {"bg_color": BG, "bg": BG_PATH, "glyph_color": GLYPH, "glyph": glyph,
                       "accent": r["accent"], "rail": RAIL_PATH}
    layer = {"scale": "%g" % GLYPH_SCALE, "offset": "%g" % GLYPH_OFFSET, "glyph": glyph}
    adaptive = ADAPTIVE % {"name": name}
    files = {
        "drawable/%s.xml" % name: legacy,
        "drawable/%s_background.xml" % name: BACKGROUND % {"bg_color": BG},
        "drawable/%s_foreground.xml" % name: FOREGROUND % dict(layer, color=GLYPH, accent=r["accent"],
                                                               rail=ADAPTIVE_RAIL_PATH),
        "drawable/%s_monochrome.xml" % name: MONOCHROME % dict(layer, color="#FFFFFFFF"),
        "mipmap-anydpi-v26/%s.xml" % name: adaptive,
        "mipmap-anydpi-v26/%s_round.xml" % name: adaptive,
    }
    if r["legacy_fallback"] == "mipmap":
        files["mipmap/%s.xml" % name] = legacy
        files["mipmap/%s_round.xml" % name] = legacy
    return {os.path.join(ROOT, r["res_dir"], rel): body for rel, body in files.items()}


def main(check):
    check_safe_zone()
    bad = 0
    count = 0
    for r in rows():
        for p, out in sorted(render(r).items()):
            count += 1
            if check:
                if not os.path.isfile(p) or open(p, encoding="utf8").read() != out:
                    print("ICON_DRIFT %s" % os.path.relpath(p, ROOT))
                    bad += 1
            else:
                os.makedirs(os.path.dirname(p), exist_ok=True)
                with open(p, "w", encoding="utf8", newline="\n") as f:
                    f.write(out)
    if check:
        print("ICON_GENERATOR_CHECK=%s files=%d drift=%d" % ("FAIL" if bad else "PASS", count, bad))
        sys.exit(1 if bad else 0)
    print("ICON_GENERATOR_WROTE files=%d" % count)


if __name__ == "__main__":
    main("--check" in sys.argv)
