#!/usr/bin/env python3
"""Derives the InScript on-screen rows of the other Indic scripts from the Devanagari InScript layout.

InScript puts the same sounds on the same keys in every Indic script, and Unicode names the parallel characters alike
(DEVANAGARI LETTER KA / GUJARATI LETTER KA); see indic_common.py. Characters a script does not have (Tamil aspirates, for
example) are dropped. The Devanagari layer and the derived scripts were checked against Indic Keyboard's InScript layouts
(Apache-2.0, github.com/smc/Indic-Keyboard). Prints a Kotlin source file to stdout.
"""
from indic_common import *

DEV_N = ["ौ ै ा ी ू ब ह ग द ज ड ़", "ो े ् ि ु प र क त च ट", "ृ ं म न व ल स य ः"]
DEV_S = ["औ ऐ आ ई ऊ भ ङ घ ध झ ढ ञ", "ओ ए अ इ उ फ ऱ ख थ छ ठ", "ऋ ँ ण ऩ ळ ऴ श ष ऽ ॐ"]
DEV_MORE = {"े": ["ॆ", "ॅ"], "ो": ["ॊ", "ॉ"], "ए": ["ऎ", "ऍ"], "ओ": ["ऒ", "ऑ"],
            "क": ["क्ष", "क़"], "ख": ["ख़"], "ग": ["ग़"], "ज": ["ज्ञ", "ज़"], "ड": ["ड़"], "ढ": ["ढ़"],
            "फ": ["फ़"], "य": ["य़"], "त": ["त्र"], "श": ["श्र"], "र": ["्र", "र्"], "ऋ": ["ॠ", "ऌ"]}
EXT_N, EXT_S = "ॆ ॊ", "ऎ ऒ"      # short e / o as ordinary keys in the four Dravidian scripts

# Hand-added long-press keys a script needs that Devanagari has no parallel for (keys are target-script characters).
EXTRA_MORE = {
    "MALAYALAM": {"ണ": ["ൺ"], "ന": ["ൻ"], "ര": ["ർ"], "ല": ["ൽ"], "ള": ["ൾ"], "ക": ["ൿ"], "ൌ": ["ൗ"]},
    "BENGALI": {"ত": ["ৎ"], "য": ["\u09DF"]},
    "GURMUKHI": {"ਅ": ["ੳ", "ੲ"], "ਂ": ["ੰ", "ੱ"], "ਜ": ["\u0A5B"], "ਫ": ["\u0A5E"], "ਖ": ["\u0A59"], "ਗ": ["\u0A5A"]},
}

def derive(row, script, ext=""):
    toks = (row + " " + ext).split()
    return " ".join(t for t in (derive_token(x, script) for x in toks) if t)

def derive_more(script, on_rows):
    out = {}
    for k, vs in DEV_MORE.items():
        if script == "TAMIL" and k != "क": continue      # Tamil only has க்ஷ; the other conjuncts are not Tamil
        dk = derive_token(k, script)
        if dk is None: continue
        dv = [v for v in (derive_token(x, script) for x in vs) if v and v not in on_rows]
        if dv: out[dk] = dv
    for k, vs in EXTRA_MORE.get(script, {}).items(): out.setdefault(k, []).extend(vs)
    return out

def kt(name, rows): return f'    val {name} = listOf(' + ", ".join('"' + r + '"' for r in rows) + ')'
def kmap(name, m): return f'    val {name} = mapOf(' + ", ".join('"%s" to listOf(%s)' % (k, ", ".join('"%s"' % x for x in v)) for k, v in m.items()) + ')'

SCRIPTS = (("guj", "GUJARATI"), ("ben", "BENGALI"), ("pan", "GURMUKHI"), ("tam", "TAMIL"), ("tel", "TELUGU"), ("kan", "KANNADA"), ("mal", "MALAYALAM"))

if __name__ == "__main__":
    print("package org.sableos.titan2.keyboard.core\n")
    print("// Generated by tools/gen_indic_rows.py from the Devanagari InScript layout. Layouts verified against Indic Keyboard (Apache-2.0).")
    print("internal object IndicRows {")
    print(kt("devN", DEV_N)); print(kt("devS", DEV_S)); print(kmap("devMore", DEV_MORE))
    for nm, script in SCRIPTS:
        short = script in SHORT_EO_SCRIPTS
        n = [derive(r, script, EXT_N if (short and i == 2) else "") for i, r in enumerate(DEV_N)]
        s = [derive(r, script, EXT_S if (short and i == 2) else "") for i, r in enumerate(DEV_S)]
        on = set(" ".join(n + s).split())
        print(kt(nm + "N", n)); print(kt(nm + "S", s)); print(kmap(nm + "More", derive_more(script, on)))
    print("}")
