#!/usr/bin/env python3
"""Writes the notice and licence bundle shipped next to pinyin_zh.tsv in the APK assets.

Usage: gen_pinyin_license_bundle.py <NOTICE out> <LICENSES out>
Deterministic (UTF-8, LF). Contains only the notices and licences for the two inputs actually used, taken from
third_party/pinyin_zh/PROVENANCE.env, with each licence text checked against its pinned sha256 first.
"""
import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PINS = {}
for _l in open(os.path.join(ROOT, 'third_party/pinyin_zh/PROVENANCE.env'), encoding='utf8'):
    _l = _l.strip()
    if _l and not _l.startswith('#') and '=' in _l:
        _k, _v = _l.split('=', 1)
        PINS[_k] = _v


def licence(prefix):
    path = os.path.join(ROOT, PINS[prefix + '_LICENSE_FILE'])
    data = open(path, 'rb').read()
    if hashlib.sha256(data).hexdigest() != PINS[prefix + '_LICENSE_SHA256']:
        sys.stderr.write('PINYIN_LICENSE_BUNDLE_FAIL: %s sha256 mismatch\n' % path)
        sys.exit(1)
    return data.decode('utf8').rstrip('\n') + '\n'


def notice():
    return (
        'pinyin_zh.tsv: notices\n'
        '======================\n\n'
        'pinyin_zh.tsv is data generated by tools/gen_pinyin_dict.py from exactly two input datasets. The generator\n'
        'is offline and deterministic; the inputs are pinned by sha256 in third_party/pinyin_zh/PROVENANCE.env.\n'
        'The full licence texts are in pinyin_zh.LICENSES.txt, shipped alongside this file.\n\n'
        '1. CC-CEDICT, https://cc-cedict.org/ , published by MDBG.\n'
        '   Snapshot: %(snap)s\n'
        '   Archive: %(art)s, sha256 %(zip)s\n'
        '   (member %(mem)s, sha256 %(memsha)s)\n'
        '   Licence: Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0),\n'
        '   https://creativecommons.org/licenses/by-sa/4.0/\n'
        '   Referenced work: CEDICT, Copyright (C) 1997, 1998 Paul Andrew Denisowski.\n\n'
        '2. Unicode Unihan Database, Unicode Version %(uver)s, Unihan_Readings.txt\n'
        '   (c) 2026 Unicode, Inc. Unicode and the Unicode Logo are registered trademarks of Unicode, Inc.\n'
        '   Archive: %(uart)s, sha256 %(uzip)s\n'
        '   (member Unihan_Readings.txt, sha256 %(ursha)s)\n'
        '   Properties used: %(props)s\n'
        '   Licence: Unicode License v3 (Unicode-3.0), https://www.unicode.org/terms_of_use.html\n\n'
        'Modifications by Sable: the data was changed from the upstream form. The generator selects the Simplified\n'
        'Chinese form of each CC-CEDICT entry, filters entries (Han characters only, one to six characters, valid\n'
        'pinyin only), normalizes pinyin (lowercase, ue-diaeresis written v, circumflex dropped), strips tones to\n'
        'form the lookup key, removes syllable separators, deduplicates readings, merges the admitted Unihan\n'
        'readings for single characters, assigns deterministic ranking weights, and sorts the result into the Sable\n'
        'runtime TSV format (pinyin<TAB>word<TAB>weight). The weight is a neutral ranking weight and is NOT a word\n'
        'frequency.\n\n'
        'Licence of the generated data: for Sable engineering and release policy the generated asset is treated\n'
        'conservatively as a CC BY-SA 4.0 derivative (%(lic)s), and the Unicode-3.0 notice is preserved for the\n'
        'Unihan-derived readings. This data asset is separate from the Sable Keyboard source-code licence. This\n'
        'file records provenance; it is not a legal opinion.\n'
    ) % {
        'snap': PINS['CC_CEDICT_SNAPSHOT'], 'art': PINS['CC_CEDICT_ARTIFACT'], 'zip': PINS['CC_CEDICT_ZIP_SHA256'],
        'mem': PINS['CC_CEDICT_MEMBER'], 'memsha': PINS['CC_CEDICT_MEMBER_SHA256'],
        'uver': PINS['UNIHAN_VERSION'], 'uart': PINS['UNIHAN_ARTIFACT'], 'uzip': PINS['UNIHAN_ZIP_SHA256'],
        'ursha': PINS['UNIHAN_READINGS_SHA256'], 'props': PINS['UNIHAN_ADMITTED_PROPERTIES'],
        'lic': PINS['PINYIN_GENERATED_CORPUS_LICENSE'],
    }


def licences():
    bar = '=' * 78
    return (
        'pinyin_zh.tsv: licence texts (CC-CEDICT and Unicode Unihan only)\n\n'
        + '\n' + bar + '\nCC-CEDICT: Creative Commons Attribution-ShareAlike 4.0 International\n' + bar + '\n\n'
        + licence('CC_CEDICT')
        + '\n' + bar + '\nUnicode Unihan Database: Unicode License v3\n' + bar + '\n\n'
        + licence('UNIHAN')
    )


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.stderr.write('usage: gen_pinyin_license_bundle.py <NOTICE out> <LICENSES out>\n')
        sys.exit(2)
    for path, text in ((sys.argv[1], notice()), (sys.argv[2], licences())):
        with open(path, 'w', encoding='utf8', newline='\n') as fh:
            fh.write(text)
