# SableOS product layer for the Zinwa Q25 on a LineageOS 23.2 base.
#
# Staged to vendor/sable/q25 by scripts/stage-product.sh and pulled in through
# LineageOS's vendor/extra/product.mk hook, which vendor/lineage/config/common.mk
# inherits before anything else. The official lineage_Q25 device tree is not
# modified.
#
# Up to Q3 nothing here is privileged: no platform certificate, no privapp
# permissions, no default-role or default-IME provisioning. Q4 adds the
# framework layer (sable-q25-framework.mk, generated): Sable Start as HOME
# (platform-signed SableLauncher) and Sable Keyboard as the only IME.

SABLE_Q25_PATH := vendor/sable/q25

# Sable identity. ro.sable.profile.id is what Sable apps read to choose device
# behaviour (keyboard layout, camera profile). Profiles never inherit another
# device's evidence.
PRODUCT_SYSTEM_EXT_PROPERTIES += \
    ro.sable.profile.id=zinwa-q25 \
    ro.sable.device=Q25 \
    ro.sable.base=lineage-23.2

-include $(SABLE_Q25_PATH)/release.mk

# Display density: the one value for the open decision in
# device-profile/DISPLAY.md. Empty keeps the LineageOS device value
# (TARGET_SCREEN_DENSITY 193, about 596 dp wide). Set it to the density chosen
# on hardware (for example 240 for 480 dp or 280 for 411 dp). It is written to
# the product partition, whose build.prop init loads after vendor's, so it
# replaces the device value. Sable layouts follow from the resulting display
# size and resource qualifiers (sw<N>dp, notlong), never from the device model.
# tests/check-sable-design.py checks the value.
SABLE_LCD_DENSITY :=
ifneq ($(SABLE_LCD_DENSITY),)
PRODUCT_PRODUCT_PROPERTIES += \
    ro.sf.lcd_density=$(SABLE_LCD_DENSITY)
endif

# Keep the LineageOS Updater from offering LineageOS OTAs, which would replace
# SableOS. The .invalid TLD never resolves (RFC 6761). Replace with a Sable OTA
# server in phase Q5.
PRODUCT_SYSTEM_EXT_PROPERTIES += \
    lineage.updater.uri=https://updates.invalid/sableos/q25/{device}/{type}/{incr}

# Sable applications. Generated by scripts/stage-product.sh from apps.tsv for the
# APKs that were actually built.
-include $(SABLE_Q25_PATH)/sable-q25-apps.mk

# Phase Q4 framework integration. Generated by scripts/stage-product.sh; empty
# before Q4.
-include $(SABLE_Q25_PATH)/sable-q25-framework.mk
