# SableOS product layer for the Zinwa Q25 on a LineageOS 23.2 base.
#
# Staged to vendor/sable/q25 by scripts/stage-product.sh and pulled in through
# LineageOS's vendor/extra/product.mk hook, which vendor/lineage/config/common.mk
# inherits before anything else. The official lineage_Q25 device tree is not
# modified.
#
# Nothing here is privileged: no platform certificate, no privapp permissions,
# no default-role or default-IME provisioning. Those are separate, evidence-driven
# steps (ROADMAP.md, phases Q3/Q4).

SABLE_Q25_PATH := vendor/sable/q25

# Sable identity. ro.sable.profile.id is what Sable apps read to choose device
# behaviour (keyboard layout, camera profile). Profiles never inherit another
# device's evidence.
PRODUCT_SYSTEM_EXT_PROPERTIES += \
    ro.sable.profile.id=zinwa-q25 \
    ro.sable.device=Q25 \
    ro.sable.base=lineage-23.2

-include $(SABLE_Q25_PATH)/release.mk

# Keep the LineageOS Updater from offering LineageOS OTAs, which would replace
# SableOS. The .invalid TLD never resolves (RFC 6761). Replace with a Sable OTA
# server in phase Q5.
PRODUCT_SYSTEM_EXT_PROPERTIES += \
    lineage.updater.uri=https://updates.invalid/sableos/q25/{device}/{type}/{incr}

# Sable applications. Generated by scripts/stage-product.sh from apps.tsv for the
# APKs that were actually built.
-include $(SABLE_Q25_PATH)/sable-q25-apps.mk
