#!/usr/bin/env python3
"""Regenerate the SableSetupWizardOverlay welcome strings from a LineageOS
SetupWizard checkout (packages/apps/SetupWizard, lineage-23.2).

Only `setup_welcome_message` is overlaid, with the product name filled in as
"SableOS", in every locale LineageOS translates. `os_name` stays "LineageOS",
so the LineageOS features page, its privacy-policy text and the Seedvault
restore text keep naming LineageOS truthfully.

    python3 scripts/gen-sable-setupwizard-strings.py <SetupWizard checkout>
"""
import pathlib
import re
import sys

PRODUCT = "SableOS"
OUT = pathlib.Path(__file__).resolve().parents[1] / "product/common/overlay/SableSetupWizardOverlay/res"
LINE = re.compile(r'<string name="setup_welcome_message">(.*)</string>')
# Translations write the argument as <xliff:g>%1$s</xliff:g>, <xliff:g>%1s</xliff:g>,
# a self-closing <xliff:g/> or a bare %1$s.
ARG = re.compile(r'<xliff:g[^>]*>%1\$?s</xliff:g>|<xliff:g[^>]*/>|%1\$s')

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/gen-sable-setupwizard-strings.py from LineageOS SetupWizard
     (lineage-23.2) translations. Do not edit by hand. -->
<resources>
"""


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    res = pathlib.Path(sys.argv[1]) / "res"
    count = 0
    for strings in sorted(res.glob("values*/strings.xml")):
        qualifier = strings.parent.name
        if qualifier not in ("values",) and not re.fullmatch(r"values-[a-z]{2,3}(-r[A-Z]{2})?", qualifier):
            continue
        for line in strings.read_text(encoding="utf-8").splitlines():
            m = LINE.search(line)
            if not m:
                continue
            text, n = ARG.subn(PRODUCT, m.group(1))
            if n != 1:
                raise SystemExit(f"{strings}: expected one %1$s in {m.group(1)!r}")
            out = OUT / qualifier / "strings.xml"
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(
                HEADER + f'    <string name="setup_welcome_message">{text}</string>\n</resources>\n',
                encoding="utf-8",
            )
            count += 1
    print(f"SETUPWIZARD_WELCOME_STRINGS={count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
