#!/usr/bin/env bash
# Inject (Q2+) or remove (Q1) the Sable product layer in the Android tree.
#
#   vendor/sable/q25/          product/q25 template + generated files + APKs
#   vendor/extra/product.mk    LineageOS hook that inherits the Sable layer
#
# The Android.bp and sable-q25-apps.mk are generated from the APK manifest that
# scripts/build-apps.sh wrote, so they name only APKs that were really built.
set -euo pipefail

# shellcheck source=build/lib/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/build/lib/common.sh"

RELEASE="${1:-}"
shift || true
sable_require_release "$RELEASE"

APPS_DIR="$SABLE_APPS_OUT/latest"
ALLOW_NO_APPS=NO
while (($#)); do
    case "$1" in
        --apps-dir) APPS_DIR="${2:-}"; shift 2 ;;
        --allow-no-apps) ALLOW_NO_APPS=YES; shift ;;
        *) sable_fail "unknown argument $1" ;;
    esac
done

sable_require_android_root
VENDOR_SABLE="$SABLE_ANDROID_ROOT/vendor/sable/q25"
EXTRA="$SABLE_ANDROID_ROOT/vendor/extra/product.mk"

if ! sable_release_has_sable_layer "$RELEASE"; then
    # Only remove what this script created.
    if [[ -f "$EXTRA" ]] && ! grep -q 'vendor/sable/q25/sable-q25.mk' "$EXTRA"; then
        sable_fail "$EXTRA was not written by this script; remove or rename it yourself"
    fi
    rm -f "$EXTRA"
    rm -rf "$VENDOR_SABLE"
    echo "STAGE=PASS"
    echo "SABLE_LAYER=REMOVED (Q1 control build)"
    exit 0
fi

if [[ -f "$EXTRA" ]] && ! grep -q 'vendor/sable/q25/sable-q25.mk' "$EXTRA"; then
    sable_fail "$EXTRA exists with other content; merge it by hand"
fi

rm -rf "$VENDOR_SABLE"
mkdir -p "$VENDOR_SABLE/prebuilt" "$(dirname "$EXTRA")"
install -m 0644 "$SABLE_REPO_ROOT/product/q25/sable-q25.mk" "$VENDOR_SABLE/sable-q25.mk"
install -m 0644 "$SABLE_REPO_ROOT/product/q25/extra-product.mk" "$EXTRA"

tool_commit="$(git -C "$SABLE_REPO_ROOT" rev-parse --verify -q HEAD 2>/dev/null || echo uncommitted)"
cat > "$VENDOR_SABLE/release.mk" <<EOF
# Generated by scripts/stage-product.sh. Do not edit.
PRODUCT_SYSTEM_EXT_PROPERTIES += \\
    ro.sable.release=$RELEASE \\
    ro.sable.build_source=$tool_commit
EOF

bp="$VENDOR_SABLE/Android.bp"
mk="$VENDOR_SABLE/sable-q25-apps.mk"
{
    echo "// Generated by scripts/stage-product.sh from product/q25/apps.tsv. Do not edit."
    echo "// Non-privileged product apps; no platform certificate."
} > "$bp"
{
    echo "# Generated by scripts/stage-product.sh. Do not edit."
    echo "PRODUCT_PACKAGES += \\"
} > "$mk"

count=0
manifest="$APPS_DIR/manifest.tsv"
if [[ -f "$manifest" ]]; then
    (cd "$APPS_DIR/prebuilt" && sha256sum -c --quiet ../SHA256SUMS.txt) || sable_fail "APK hashes don't match $APPS_DIR/SHA256SUMS.txt"
    while IFS=$'\t' read -r module group package signing overrides filename sha; do
        [[ "$module" == module ]] && continue
        install -m 0644 "$APPS_DIR/prebuilt/$filename" "$VENDOR_SABLE/prebuilt/$filename"
        {
            echo
            echo "// $group app $package sha256=$sha"
            echo "android_app_import {"
            echo "    name: \"$module\","
            echo "    apk: \"prebuilt/$filename\","
            if [[ "$signing" == presigned ]]; then
                echo "    presigned: true,"
            else
                echo "    default_dev_cert: true,"
            fi
            echo "    product_specific: true,"
            echo "    privileged: false,"
            if [[ "$overrides" != - && -n "$overrides" ]]; then
                printf '    overrides: [%s],\n' "$(sed 's/[^,][^,]*/"&"/g; s/,/, /g' <<<"$overrides")"
            fi
            echo "    dex_preopt: {"
            echo "        enabled: false,"
            echo "    },"
            echo "}"
        } >> "$bp"
        echo "    $module \\" >> "$mk"
        count=$((count + 1))
    done < "$manifest"
    cp "$manifest" "$VENDOR_SABLE/apps-manifest.tsv"
fi
echo "" >> "$mk"

if (( count == 0 )) && [[ "$ALLOW_NO_APPS" != YES ]]; then
    sable_fail "no Sable APKs at $APPS_DIR (run 'apps' first, or pass --allow-no-apps for a props-only layer)"
fi

echo "STAGE=PASS"
echo "SABLE_LAYER=STAGED"
echo "VENDOR_SABLE=$VENDOR_SABLE"
echo "APP_COUNT=$count"
